- name: Set connection specific variables
  set_fact:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: 'zabbix'  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu

# If you want to use Username and Password to be authenticated by Zabbix Server
- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix

- name: Create new global macro or update an existing macro's value
  community.zabbix.zabbix_globalmacro:
    macro_name: test.MACRO
    macro_value: test
    macro_type: text
    macro_description: Example description
    state: present
# Values with curly brackets need to be quoted otherwise they will be interpreted as a dictionary

- name: Create new global macro in Zabbix native format with Secret Type
  community.zabbix.zabbix_globalmacro:
    macro_name: "{$EXAMPLE.MACRO}"
    macro_value: Example value
    macro_type: secret
    macro_description: Example description
    state: present

#- name: Delete existing global macro
#  community.zabbix.zabbix_globalmacro:
#    macro_name: "{$EXAMPLE.MACRO}"
#    state: absent
